version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing zip utility..."
      - yum install -y zip
      - echo "Changing into frontend directory"
      - cd frontend

  pre_build:
    commands:
      - echo "Installing frontend dependencies..."
      - npm ci
      - echo "Creating .env.local with API Gateway URL..."
      - echo "NEXT_PUBLIC_API_BASE_URL=$API_GATEWAY_URL" > .env.local
      - echo "Environment configured with API Gateway URL: $API_GATEWAY_URL"
      - echo "Contents of .env.local file:"
      - cat .env.local

  build:
    commands:
      - echo "Building Next.js application..."
      - npm run build
      - echo "Creating deployment package..."
      - cd out && zip -r build.zip .
      - echo "Next.js build completed successfully"

  post_build:
    commands:
      - echo "Deploying frontend to Amplify..."
      - echo $AMPLIFY_APP_ID
      - echo "Creating Amplify deployment..."
      - >-
        aws amplify create-deployment \
          --app-id $AMPLIFY_APP_ID \
          --branch-name frontend-deployment-integration \
          --output json > deployment_response.json
      - echo "Extracting upload URL and job ID..."
      - export UPLOAD_URL=$(node -e "const data=require('./deployment_response.json'); console.log(data.zipUploadUrl)")
      - export JOB_ID=$(node -e "const data=require('./deployment_response.json'); console.log(data.jobId)")
      - echo "Uploading build.zip to Amplify..."
      - curl -X PUT -T build.zip "$UPLOAD_URL"
      - echo "Starting deployment..."
      - >-
        aws amplify start-deployment \
          --app-id $AMPLIFY_APP_ID \
          --branch-name frontend-deployment-integration \
          --job-id $JOB_ID
      - echo "Frontend deployment initiated successfully!"